@once
    @push('styles')
        <style>
            /* Input focus styles using CSS variables */
            .block.w-full.border.rounded-md:focus {
                @apply outline-none ring-1;
                border-color: var(--color-accent);
                --tw-ring-color: var(--color-accent);
            }

            .dark .block.w-full.border.rounded-md:focus {
                border-color: var(--color-accent-content);
                --tw-ring-color: var(--color-accent-content);
            }
        </style>
    @endpush
@endonce

<div>
    @if($label)
        <label for="{{ $inputId }}" class="{{ $error ? 'text-red-600 dark:text-red-400' : '' }}">
            {{ $label }}
            @if($required)
                <span class="text-red-600 dark:text-red-400">*</span>
            @endif
        </label>
    @endif

    <div class="relative {{ $label ? 'mt-2' : '' }}">
        @if($icon && $iconPosition === 'left')
            <div class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 dark:text-gray-400 pointer-events-none">
                <i class="fas fa-{{ $icon }}"></i>
            </div>
            <input 
                type="{{ $type }}" 
                name="{{ $name }}" 
                id="{{ $inputId }}"
                value="{{ is_string($value) ? $value : '' }}"
                placeholder="{{ $placeholder }}"
                @if($required) required @endif
                @if($disabled) disabled @endif
                @if($readonly) readonly @endif
                class="{{ $classes }}"
                @if($slugFrom) data-slug-from="{{ $slugFrom }}" @endif
                {{ $attributes->except(['class', 'value']) }}
            >
        @elseif($icon && $iconPosition === 'right')
            <input 
                type="{{ $type }}" 
                name="{{ $name }}" 
                id="{{ $inputId }}"
                value="{{ is_string($value) ? $value : '' }}"
                placeholder="{{ $placeholder }}"
                @if($required) required @endif
                @if($disabled) disabled @endif
                @if($readonly) readonly @endif
                class="{{ $classes }}"
                @if($slugFrom) data-slug-from="{{ $slugFrom }}" @endif
                {{ $attributes->except(['class', 'value']) }}
            >
            <div class="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 dark:text-gray-400 pointer-events-none">
                <i class="fas fa-{{ $icon }}"></i>
            </div>
        @else
            <input 
                type="{{ $type }}" 
                name="{{ $name }}" 
                id="{{ $inputId }}"
                value="{{ is_string($value) ? $value : '' }}"
                placeholder="{{ $placeholder }}"
                @if($required) required @endif
                @if($disabled) disabled @endif
                @if($readonly) readonly @endif
                class="{{ $classes }}"
                @if($slugFrom) data-slug-from="{{ $slugFrom }}" @endif
                {{ $attributes->except(['class', 'value']) }}
            >
        @endif
    </div>

    @if($hint && !$error)
        <div class="text-xs leading-4 tracking-[0.4px] text-gray-600 dark:text-gray-400 mt-1.5">{{ $hint }}</div>
    @endif

    @if($error && $errorMessage)
        <div class="text-xs leading-4 tracking-[0.4px] text-red-600 dark:text-red-400 flex items-center gap-1 mt-1.5">
            <i class="fas fa-exclamation-circle"></i>
            {{ $errorMessage }}
        </div>
    @endif
</div>

@if($slugFrom)
@once
@push('scripts')
<script>
(function() {
    'use strict';
    function generateSlug(text) {
        if (!text) return '';
        return text.toLowerCase()
            .replace(/[^a-z0-9 -]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-+|-+$/g, '');
    }
    function initSlugInput(slugInput) {
        var sourceId = slugInput.getAttribute('data-slug-from');
        if (!sourceId) return;
        var sourceInput = document.getElementById(sourceId);
        if (!sourceInput || slugInput._slugInitialized) return;
        slugInput._slugInitialized = true;
        var currentSource = sourceInput.value || '';
        var currentSlug = slugInput.value || '';
        slugInput.dataset.autoGenerated = (currentSlug === generateSlug(currentSource) || !currentSlug) ? 'true' : 'false';
        sourceInput.addEventListener('input', function() {
            if (slugInput.dataset.autoGenerated === 'true' || !slugInput.value) {
                slugInput.value = generateSlug(this.value);
                slugInput.dataset.autoGenerated = 'true';
                slugInput.dispatchEvent(new Event('input', { bubbles: true }));
            }
        });
        slugInput.addEventListener('input', function() {
            var gen = generateSlug(sourceInput.value);
            slugInput.dataset.autoGenerated = (this.value === gen) ? 'true' : 'false';
            if (!this.value) slugInput.dataset.autoGenerated = 'true';
        });
    }
    function runSlugInits() {
        document.querySelectorAll('input[data-slug-from]').forEach(initSlugInput);
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', runSlugInits);
    } else {
        runSlugInits();
    }
    if (typeof Livewire !== 'undefined') {
        Livewire.hook('morph.updated', function() { setTimeout(runSlugInits, 50); });
    }
})();
</script>
@endpush
@endonce
@endif
