@once
<script>
(function() {
    'use strict';
    function generateSlug(text) {
        if (!text) return '';
        return text.toLowerCase()
            .replace(/[^a-z0-9 -]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-+|-+$/g, '');
    }
    function initSlugInput(slugInput) {
        var sourceId = slugInput.getAttribute('data-slug-from');
        if (!sourceId) return;
        var sourceInput = document.getElementById(sourceId);
        if (!sourceInput || slugInput._slugInitialized) return;
        slugInput._slugInitialized = true;
        var currentSource = sourceInput.value || '';
        var currentSlug = slugInput.value || '';
        slugInput.dataset.autoGenerated = (currentSlug === generateSlug(currentSource) || !currentSlug) ? 'true' : 'false';
        sourceInput.addEventListener('input', function() {
            if (slugInput.dataset.autoGenerated === 'true' || !slugInput.value) {
                slugInput.value = generateSlug(this.value);
                slugInput.dataset.autoGenerated = 'true';
                slugInput.dispatchEvent(new Event('input', { bubbles: true }));
            }
        });
        slugInput.addEventListener('input', function() {
            var gen = generateSlug(sourceInput.value);
            slugInput.dataset.autoGenerated = (this.value === gen) ? 'true' : 'false';
            if (!this.value) slugInput.dataset.autoGenerated = 'true';
        });
    }
    function runSlugInits() {
        document.querySelectorAll('input[data-slug-from]').forEach(initSlugInput);
    }
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', runSlugInits);
    } else {
        runSlugInits();
    }
    if (typeof Livewire !== 'undefined') {
        Livewire.hook('morph.updated', function() { setTimeout(runSlugInits, 50); });
    }
})();
</script>
@endonce
