<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\AdminBaseController;
use App\Http\Requests\ChangelogRequest;
use App\Models\Changelog;
use Illuminate\Http\Request;

class ChangelogController extends AdminBaseController
{
    /**
     * Display a listing of the resource.
     * Table is rendered by Livewire admin.table component.
     */
    public function index()
    {
        return view('admin.changelog.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.changelog.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ChangelogRequest $request)
    {
        try {
            $validated = $request->validated();
            $validated = $this->purifyHtmlKeys($validated, ['description', 'content']);

            // Handle array fields - filter out empty values and ensure they're arrays
            $features = $request->input('features', []);
            if (is_array($features)) {
                $features = array_values(array_filter($features, function($feature) {
                    return !empty(trim($feature));
                }));
            } else {
                $features = [];
            }

            $steps = $request->input('steps', []);
            if (is_array($steps)) {
                $steps = array_values(array_filter($steps, function($step) {
                    return !empty(trim($step));
                }));
            } else {
                $steps = [];
            }

            $validated['features'] = $features;
            $validated['steps'] = $steps;

            // Set default values
            $validated['is_active'] = $request->has('is_active');
            $validated['sort_order'] = $validated['sort_order'] ?? 0;

            // If no slug provided, it will be auto-generated by the Sluggable trait
            if (empty($validated['slug'])) {
                unset($validated['slug']);
            }

            $changelog = Changelog::create($validated);

            return redirect()
                ->route('admin.content.changelog.index')
                ->with('success', 'Changelog entry created successfully.');

        } catch (\Exception $e) {
            return redirect()
                ->back()
                ->withInput()
                ->withErrors(['error' => 'An error occurred while creating the changelog entry: '.$e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Changelog $changelog)
    {
        return view('admin.changelog.show', compact('changelog'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Changelog $changelog)
    {
        return view('admin.changelog.edit', compact('changelog'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ChangelogRequest $request, Changelog $changelog)
    {
        try {
            $validated = $request->validated();
            $validated = $this->purifyHtmlKeys($validated, ['description', 'content']);

            // Handle array fields - filter out empty values and ensure they're arrays
            $features = $request->input('features', []);
            if (is_array($features)) {
                $features = array_values(array_filter($features, function($feature) {
                    return !empty(trim($feature));
                }));
            } else {
                $features = [];
            }

            $steps = $request->input('steps', []);
            if (is_array($steps)) {
                $steps = array_values(array_filter($steps, function($step) {
                    return !empty(trim($step));
                }));
            } else {
                $steps = [];
            }

            $validated['features'] = $features;
            $validated['steps'] = $steps;

            // Set default values
            $validated['is_active'] = $request->has('is_active');
            $validated['sort_order'] = $validated['sort_order'] ?? $changelog->sort_order;

            // If no slug provided, keep the existing one or let it auto-generate
            if (empty($validated['slug'])) {
                unset($validated['slug']);
            }

            $changelog->update($validated);

            return redirect()
                ->route('admin.content.changelog.index')
                ->with('success', 'Changelog entry updated successfully.');

        } catch (\Exception $e) {
            return redirect()
                ->back()
                ->withInput()
                ->withErrors(['error' => 'An error occurred while updating the changelog entry: '.$e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Changelog $changelog)
    {
        try {
            $changelog->delete();

            return redirect()
                ->route('admin.content.changelog.index')
                ->with('success', 'Changelog entry deleted successfully.');

        } catch (\Exception $e) {
            return redirect()
                ->back()
                ->withErrors(['error' => 'An error occurred while deleting the changelog entry: '.$e->getMessage()]);
        }
    }

    /**
     * Update the order of changelog entries.
     */
    public function updateOrder(Request $request)
    {
        $request->validate([
            'items' => 'required|array',
            'items.*.id' => 'required|exists:changelogs,id',
            'items.*.sort_order' => 'required|integer|min:0',
        ]);

        try {
            foreach ($request->items as $item) {
                Changelog::where('id', $item['id'])
                    ->update(['sort_order' => $item['sort_order']]);
            }

            // Clear cache
            Changelog::clearCache();

            return response()->json(['success' => true]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'An error occurred while updating the order: '.$e->getMessage(),
            ], 500);
        }
    }
}
